# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Era.destroy_all
Artist.destroy_all

early = Era.create(name: "Early Jazz/New Orleans and Chicago Dixieland")
swing = Era.create(name: "Swing/Big Band")
bebop = Era.create(name: "Bebop")
cool = Era.create(name: "Cool")
hard_bop = Era.create(name: "Hard Bop")
free_jazz = Era.create(name: "Free Jazz/Avant Garde")
fusion = Era.create(name: "Fusion/Jazz-Rock")
eclectic = Era.create(name: "Eclecticisim")


Artist.create(name: "Louis Armstrong", album: "St. Louis Blues", bio: "Armstrong was born and raised in New Orleans. Coming to prominence in the 1920s as an inventive trumpet and cornet player, Armstrong was a foundational influence in jazz, shifting the focus of the music from collective improvisation to solo performance.[4] Around 1922, he followed his mentor, Joe Oliver, to Chicago to play in the Creole Jazz Band. In Chicago, he spent time with other popular jazz musicians, reconnecting with his friend Bix Beiderbecke and spending time with Hoagy Carmichael and Lil Hardin. He earned a reputation at 'cutting contests 'and his fame reached band leader Fletcher Henderson. Henderson persuaded Armstrong to come to New York City, where he became a featured and musically influential band soloist and recording artist. Hardin became Armstrong's second wife and they returned to Chicago to play together and then he began to form his own 'Hot' jazz bands. After years of touring, he settled in Queens, and by the 1950s, he was a national musical icon, assisted in part, by his appearances on radio and in film and television, in addition to his concerts.", url: "https://www.youtube.com/watch?v=8IJzYAda1wA",era: early)
Artist.create(name: "Leon Bismark 'Bix' Beiderbecke", album: "Georgia on My Mind", bio: "Beiderbecke was one of the most influential jazz soloists of the 1920s, a cornet player noted for an inventive lyrical approach and purity of tone, with such clarity of sound that one contemporary famously described it like 'shooting bullets at a bell'. His solos on seminal recordings such as 'Singin the Blues' and 'I'm Coming, Virginia'(both 1927) demonstrate a gift for extended improvisation that heralded the jazz ballad style, in which jazz solos are an integral part of the composition. Moreover, his use of extended chords and an ability to improvise freely along harmonic as well as melodic lines are echoed in post-WWII developments in jazz. 'In a Mist' (1927) is the best known of Beiderbecke's published piano compositions, and the only one that he recorded. His piano style reflects both jazz and classical (mainly impressionist) influences. All five of his piano compositions were published by Robbins Music during his lifetime.", url: "https://www.youtube.com/watch?v=pob7zgAWeMI", era: early)
Artist.create(name: "Jelly Roll Morton", album: "Red Hot Peppers Session: Birth of the Hot, The Classic Red Hot Peppers Sessions", bio: "Ferdinand Joseph LaMothe (September 20, c. 1890 – July 10, 1941), known professionally as Jelly Roll Morton, was an American ragtime and jazz pianist, bandleader, and composer. Morton was jazz's first arranger, proving that a genre rooted in improvisation could retain its essential characteristics when notated.[2] His composition 'Jelly Roll Blues', published in 1915, was one of the first published jazz compositions. Morton also wrote 'King Porter Stomp', 'Wolverine Blues', 'Black Bottom Stomp', and 'I Thought I Heard Buddy Bolden Say', the last a tribute to New Orleans musicians from the turn of the 20th century.", url: "https://www.youtube.com/watch?v=MkGjDbKauVo", era: early)
Artist.create(name: "Sidney Bechet", album: "Texas Moaner Blues", bio: "Sidney Joseph Bechet[1] (May 14, 1897 – May 14, 1959) was an American jazz saxophonist, clarinetist, and composer. He was one of the first important soloists in jazz, beating trumpeter Louis Armstrong to the recording studio by several months. His erratic temperament hampered his career, and not until the late 1940s did he earn wide acclaim.", url: "https://www.youtube.com/watch?v=REYLNs0rh-g", era: early)
Artist.create(name: "Earl 'Fatha' Hines ", album: "Earl Hines ", bio: "Earl Kenneth Hines, also known as Earl 'Fatha'[nb 1] Hines (December 28, 1903[nb 2] – April 22, 1983), was an American jazz pianist and bandleader. He was one of the most influential figures in the development of jazz piano and, according to one source, 'one of a small number of pianists whose playing shaped the history of jazz", url: "https://www.youtube.com/watch?v=TaD4qwztS5M", era: early)


Artist.create(name: "Duke Ellington", album: "The Ellington Suites", bio: "Edward Kennedy 'Duke' Ellington (April 29, 1899 – May 24, 1974) was an American composer, pianist, and leader of a jazz orchestra, which he led from 1923 until his death over a career spanning more than six decades.[1]
Born in Washington, D.C., Ellington was based in New York City from the mid-1920s onward and gained a national profile through his orchestra's appearances at the Cotton Club in Harlem. In the 1930s, his orchestra toured in Europe. Although widely considered a pivotal figure in the history of jazz, Ellington embraced the phrase 'beyond category' as a liberating principle and referred to his music as part of the more general category of American Music.",url: "https://www.youtube.com/watch?v=qDQpZT3GhDg", era: swing)
Artist.create(name: "Count Basie", album: "Count Basie in Kansas City", bio: "William James 'Count' Basie (/ˈbeɪsi/; August 21, 1904 – April 26, 1984)[1] was an American jazz pianist, organist, bandleader, and composer. In 1935, Basie formed his own jazz orchestra, the Count Basie Orchestra, and in 1936 took them to Chicago for a long engagement and their first recording. He led the group for almost 50 years, creating innovations like the use of two 'split' tenor saxophones, emphasizing the rhythm section, riffing with a big band, using arrangers to broaden their sound, and others. Many musicians came to prominence under his direction, including the tenor saxophonists Lester Young and Herschel Evans, the guitarist Freddie Green, trumpeters Buck Clayton and Harry 'Sweets' Edison, plunger trombonist Al Grey, and singers Jimmy Rushing, Helen Humes, Thelma Carpenter, and Joe Williams.", url: "https://www.youtube.com/watch?v=hHMYhajNtNg", era: swing)
Artist.create(name: "Coleman Hawkins", album: "Rainbow Mist", bio: "Coleman Randolph Hawkins (November 21, 1904 – May 19, 1969), nicknamed 'Hawk' and sometimes 'Bean', was an American jazz tenor saxophonist.[1] One of the first prominent jazz musicians on his instrument, as Joachim E. Berendt explained: 'there were some tenor players before him, but the instrument was not an acknowledged jazz horn'. Hawkins biographer John Chilton described the prevalent styles of tenor saxophone solos prior to Hawkins as 'mooing' and 'bery belches.' Hawkins cited as influences Happy Caldwell, Stump Evans, and Prince Robinson, although he was the first to tailor his method of improvisation to the saxophone rather than imitate the techniques of the clarinet. Hawkins' virtuosic, arpeggiated approach to improvisation, with his characteristic rich, emotional, loud, and vibrato-laden tonal style, was the main influence on a generation of tenor players that included Chu Berry, Charlie Barnet, Tex Beneke, Ben Webster, Vido Musso, Herschel Evans, Buddy Tate, and Don Byas, and through them the later tenormen, Arnett Cobb, Illinois Jacquet, Flip Phillips, Ike Quebec, Al Sears,[4] Paul Gonsalves, and Lucky Thompson.[5] While Hawkins became well known with swing music during the big band era, he had a role in the development of bebop in the 1940s.", url: "https://www.youtube.com/watch?v=r1dAnw74so0", era: swing)
Artist.create(name: "Lester Young", album: "It Don't Mean a Thing", bio: "Lester Willis Young (August 27, 1909 – March 15, 1959), nicknamed 'Pres' or 'Prez', was an American jazz tenor saxophonist and occasional clarinetist.

Coming to prominence while a member of Count Basie's orchestra, Young was one of the most influential players on his instrument. In contrast to many of his hard-driving peers, Young played with a relaxed, cool tone and used sophisticated harmonies, using what one critic called 'a free-floating style, wheeling and diving like a gull, banking with low, funky riffs that pleased dancers and listeners alike'.", url: "https://www.youtube.com/watch?v=ohCOIPjyXZM", era: swing)
Artist.create(name: "Roy Eldridge", album: "The Big Band of Little Jazz ", bio: "David Roy Eldridge (January 30, 1911 – February 26, 1989), nicknamed 'Little Jazz', was an American jazz trumpet player. His sophisticated use of harmony, including the use of tritone substitutions, his virtuosic solos exhibiting a departure from the dominant style of jazz trumpet innovator Louis Armstrong, and his strong impact on Dizzy Gillespie mark him as one of the most influential musicians of the swing era and a precursor of bebop.", url: "https://www.youtube.com/watch?v=weCyhlrnXWY", era: swing)


Artist.create(name: "Dizzy Gilespie", album: "Groovin High", bio: "John Birks 'Dizzy' Gillespie (/ɡɪˈlɛspi/; October 21, 1917 – January 6, 1993) was an American jazz trumpeter, bandleader, composer, educator and singer.[2] He was a trumpet virtuoso and improviser, building on the virtuoso style of Roy Eldridge[3] but adding layers of harmonic and rhythmic complexity previously unheard in jazz. His combination of musicianship, showmanship, and wit made him a leading popularizer of the new music called bebop. His beret and horn-rimmed spectacles, his scat singing, his bent horn, pouched cheeks, and his light-hearted personality provided some of bebop's most prominent symbols.", url: "https://www.youtube.com/watch?v=2uLpjp7xkyI",era: bebop)
Artist.create(name: "Charlie Parker", album: "Billie's Bounce", bio: "Charles 'Charlie' Parker Jr. (August 29, 1920 – March 12, 1955), nicknamed 'Bird' and 'Yardbird', was an American jazz saxophonist and composer.[1] Parker was a highly influential soloist and leading figure in the development of bebop,[2] a form of jazz characterized by fast tempos, virtuosic technique, and advanced harmonies. Parker was a blazingly fast virtuoso and introduced revolutionary harmonic ideas into jazz, including rapid passing chords, new variants of altered chords, and chord substitutions. Primarily a player of the alto saxophone, Parker's tone ranged from clean and penetrating to sweet and somber.", url: "https://www.youtube.com/watch?v=02apSoxB7B4", era: bebop)
Artist.create(name: "Bud Powell", album: "The Best of Bud Powell", bio: "Earl Rudolph 'Bud' Powell (September 27, 1924 – July 31, 1966) was an American jazz pianist and composer. Along with Charlie Parker, Thelonious Monk, and Dizzy Gillespie, Powell was a leading figure in the development of bebop. His virtuosity led many to call him the Charlie Parker of the piano.[1] Powell was also a composer, and many jazz critics credit his works and his playing as having 'greatly extended the range of jazz harmony.'", url: "https://www.youtube.com/watch?v=TaSDinL6pC8", era: bebop)
Artist.create(name: "Thelonious Monk", album: "Monk's Music", bio: "Thelonious Sphere Monk[2] (/θəˈloʊniəs/, October 10, 1917[3] – February 17, 1982) was an American jazz pianist and composer. He had a unique improvisational style and made numerous contributions to the standard jazz repertoire, including ''Round Midnight', 'Blue Monk', 'Straight, No Chaser', 'Ruby, My Dear', 'In Walked Bud', and 'Well, You Neednt'. Monk is the second-most-recorded jazz composer after Duke Ellington.[4]", url: "https://www.youtube.com/watch?v=5o59Nsw7wxU", era: bebop)
Artist.create(name: "Max Roach", album: "Best Coast Jazz", bio: "Maxwell Lemuel Roach (January 10, 1924 – August 16, 2007) was an American jazz drummer and composer. A pioneer of bebop, he worked in many other styles of music, and is generally considered one of the most important drummers in history.[1][2] He worked with many famous jazz musicians, including Coleman Hawkins, Dizzy Gillespie, Charlie Parker, Miles Davis, Duke Ellington, Thelonious Monk, Abbey Lincoln, Dinah Washington, Charles Mingus, Billy Eckstine, Stan Getz, Sonny Rollins, Eric Dolphy, and Booker Little. He was inducted into the DownBeat Hall of Fame in 1980 and the Modern Drummer Hall of Fame in 1992.", url: "https://www.youtube.com/watch?v=-gNnrMZL6Uw", era: bebop)
Artist.create(name: "Dexter Gordon", album: "Dexter Rides Again", bio: "Dexter Gordon (February 27, 1923 – April 25, 1990) was an American jazz tenor saxophonist. He was among the most influential early bebop musicians, which included other greats such as Charlie Parker, Dizzy Gillespie, and Bud Powell. Gordon's height was 6 feet 6 inches (198 cm), so he was also known as 'Long Tall Dexter' and 'Sophisticated Giant'. His studio and performance career spanned over 40 years.", url: "https://www.youtube.com/watch?v=r0vhqDCy9eQ", era: bebop)
Artist.create(name: "J.J Johnson", album: "Modern Jazz Trombones", bio: "James Louis Johnson (January 22, 1924 – February 4, 2001)[1] was an American jazz trombonist, composer and arranger.

Johnson was one of the earliest trombonists to embrace bebop.", url: "https://www.youtube.com/watch?v=1ZGeYR8b-mg", era: bebop)


Artist.create(name: "Miles Davis", album: "Kind of Blue", bio: "Miles Dewey Davis III (May 26, 1926 – September 28, 1991) was an American jazz trumpeter, bandleader, and composer. He is among the most influential and acclaimed figures in the history of jazz and 20th-century music. Davis adopted a variety of musical directions in a five-decade career that kept him at the forefront of many major stylistic developments in jazz.[1]

Born in Alton, Illinois, and raised in East St. Louis, Davis left to study at the Juilliard School in New York City, before dropping out and making his professional debut as a member of saxophonist Charlie Parker's bebop quintet from 1944 to 1948. Shortly after, he recorded the Birth of the Cool sessions for Capitol Records, which were instrumental to the development of cool jazz. In the early 1950s, Miles Davis recorded some of the earliest hard bop music while on Prestige Records but did so haphazardly due to a heroin addiction. After a widely acclaimed comeback performance at the Newport Jazz Festival in 1955, he signed a long-term contract with Columbia Records and recorded the 1957 album 'Round About Midnight.[2] It was his first work with saxophonist John Coltrane and bassist Paul Chambers, key members of the sextet he led into the early 1960s. During this period, he alternated between orchestral jazz collaborations with arranger Gil Evans, such as the Spanish music-influenced Sketches of Spain (1960), and band recordings, such as Milestones (1958) and Kind of Blue (1959).[3] The latter recording remains one of the most popular jazz albums of all time,[4] having sold over five million copies in the U.S.", url: "https://www.youtube.com/watch?v=zqNTltOGh5c", era: cool)
Artist.create(name: "David Brubeck", album: "Time Out", bio: "David Warren Brubeck (/ˈbruːbɛk/; December 6, 1920 – December 5, 2012) was an American jazz pianist and composer, considered one of the foremost exponents of cool jazz. Many of his compositions have become jazz standards including 'In Your Own Sweet Way' and 'The Duke'. Brubeck's style ranged from refined to bombastic, reflecting both his mother's classical training and his own improvisational skills. His music is known for employing unusual time signatures as well as superimposing contrasting rhythms, meters, and tonalities.

Brubeck experimented with time signatures throughout his career, recording 'Pick Up Sticks' in 6
4, 'Unsquare Dance' in 7
4, 'World's Fair' in 13
4, and 'Blue Rondo à la Turk' in 9
8. He was also a composer of orchestral and sacred music and wrote soundtracks for television, such as Mr. Broadway and the animated miniseries This Is America, Charlie Brown.

Often incorrectly attributed to Brubeck, the song 'Take Five', which has become a jazz standard, was composed by Brubeck's long-time musical partner, alto saxophonist Paul Desmond.[1] Appearing on one of the top-selling jazz albums, Time Out, and written in 5
4 time, 'Take Five' has endured as a jazz classic associated with Brubeck", url: "https://www.youtube.com/watch?v=tT9Eh8wNMkw", era: cool)
Artist.create(name: "Paul Desmond", album: "Time Out", bio: "Paul Desmond (born Paul Emil Breitenfeld, November 25, 1924 – May 30, 1977) was an American jazz alto saxophonist and composer, best known for his work with the Dave Brubeck Quartet and for composing that group's biggest hit, 'Take Five'. He was one of the most popular musicians to come out of the cool jazz scene.

In addition to his work with Brubeck, he led several groups and collaborated with Gerry Mulligan, Chet Baker, Jim Hall, and Ed Bickert. After years of chain smoking and poor health, Desmond succumbed to lung cancer in 1977 after a tour with Brubeck.", url: "https://www.youtube.com/watch?v=j9GgmGLPbWU", era: cool)
Artist.create(name: "Gerry Mulligan", album: "Paris Concert", bio: "Gerald Joseph Mulligan (April 6, 1927 – January 20, 1996), also known as Jeru,[1] was an American jazz saxophonist, clarinetist, composer and arranger.[2] Though primarily known as one of the leading jazz baritone saxophonists—playing the instrument with a light and airy tone in the era of cool jazz—Mulligan was also a significant arranger, working with Claude Thornhill, Miles Davis, Stan Kenton, and others. His pianoless quartet of the early 1950s with trumpeter Chet Baker is still regarded as one of the best cool jazz groups. Mulligan was also a skilled pianist and played several other reed instruments. Several of his compositions, such as 'Walkin' Shoes' and 'Five Brothers', have become standards.", url: "https://www.youtube.com/watch?v=7DCQVyD3whM", era: cool)
Artist.create(name: "Modern Jazz Quintet", album: "The Modern Jazz Quintet", bio: "The Modern Jazz Quartet (MJQ) was a jazz combo established in 1952 that played music influenced by classical, cool jazz, blues and bebop. For most of its history the Quartet consisted of John Lewis (piano), Milt Jackson (vibraphone), Percy Heath (double bass), and Connie Kay (drums). The group grew out of the rhythm section of Dizzy Gillespie's big band from 1946 to 1948, which consisted of Lewis and Jackson along with bassist Ray Brown and drummer Kenny Clarke. They recorded as the Milt Jackson Quartet in 1951 and Brown left the group, being replaced on bass by Heath. During the early-to-mid-1950s they became the Modern Jazz Quartet, Lewis became the group's musical director, and they made several recordings with Prestige Records, including the original versions of their two best-known compositions, Lewis's 'Django' and Jackson's 'Bags' Groove'. Clarke left the group in 1955 and was replaced as drummer by Connie Kay, and in 1956 they moved to Atlantic Records and made their first tour to Europe.", url: "https://www.youtube.com/watch?v=e2gL8Zs4e3c", era: cool)
Artist.create(name: "Stan Getz", album: "Desafinado", bio: "Stanley Getz (February 2, 1927 – June 6, 1991) was an American jazz saxophonist, professionally known as Stan Getz. Playing primarily the tenor saxophone, Getz was known as 'The Sound' because of his warm, lyrical tone, his prime influence being the wispy, mellow timbre of his idol, Lester Young. Coming to prominence in the late 1940s with Woody Herman's big band, Getz is described by critic Scott Yanow as 'one of the all-time great tenor saxophonists'.[1] Getz performed in bebop and cool jazz groups. Influenced by João Gilberto and Antônio Carlos Jobim, he popularized bossa nova in America with the hit single 'The Girl from Ipanema'", url: "https://www.youtube.com/watch?v=sVdaFQhS86E", era: cool)
Artist.create(name: "Gil Evans", album: "Gil Evans and 10", bio: "Ian Ernest Gilmore Evans (born Green; May 13, 1912 – March 20, 1988)[1] was a Canadian-American jazz pianist, arranger, composer and bandleader. He is widely recognized as one of the greatest orchestrators in jazz, playing an important role in the development of cool jazz, modal jazz, free jazz, and jazz fusion. He is best known for his acclaimed collaborations with Miles Davis.", url: "https://www.youtube.com/watch?v=cL3A-o2D7pU", era: cool)

Artist.create(name: "Art Blakey and the Jazz Messengers", album: "Moaning", bio: "Arthur Blakey (October 11, 1919 – October 16, 1990) was an American jazz drummer and bandleader. He was briefly known as Abdullah Ibn Buhaina after he converted to Islam for a short time in the late 1940s.[1]

Blakey made a name for himself in the 1940s in the big bands of Fletcher Henderson and Billy Eckstine. He then worked with bebop musicians Thelonious Monk, Charlie Parker, and Dizzy Gillespie. In the mid-1950s, Horace Silver and Blakey formed the Jazz Messengers, a group that the drummer was associated with for the next 35 years. The group was formed as a collective of contemporaries, but over the years the band became known as an incubator for young talent, including Freddie Hubbard, Wayne Shorter, Lee Morgan, Benny Golson, Kenny Dorham, Hank Mobley, Donald Byrd, Jackie McLean, Johnny Griffin, Curtis Fuller, Chuck Mangione, Chick Corea, Keith Jarrett, Cedar Walton, Woody Shaw, Terence Blanchard, and Wynton Marsalis. The Biographical Encyclopedia of Jazz calls the Jazz Messengers 'the archetypal hard bop group of the late 50s'.", url: "https://www.youtube.com/watch?v=uKOoxgI_xfQ", era: hard_bop)
Artist.create(name: "Horace Silver", album: "Song for My Father", bio: "Horace Ward Martin Tavares Silver[note 1] (September 2, 1928 – June 18, 2014) was an American jazz pianist, composer, and arranger, particularly in the hard bop style that he helped pioneer in the 1950s.

After playing tenor saxophone and piano at school in Connecticut, Silver got his break on piano when his trio was recruited by Stan Getz in 1950. Silver soon moved to New York City, where he developed a reputation as a composer and for his bluesy playing. Frequent sideman recordings in the mid-1950s helped further, but it was his work with the Jazz Messengers, co-led by Art Blakey, that brought both his writing and playing most attention. Their Horace Silver and the Jazz Messengers album contained Silver's first hit, 'The Preacher'. After leaving Blakey in 1956, Silver formed his own quintet, with what became the standard small group line-up of tenor saxophone, trumpet, piano, bass, and drums. Their public performances and frequent recordings for Blue Note Records increased Silver's popularity, even through changes of personnel. His most successful album was Song for My Father, made with two iterations of the quintet in 1963 and 1964.", url: "https://www.youtube.com/watch?v=NFjmWI-d6d4", era: hard_bop)
Artist.create(name: "Sonny Rollins", album: "St Thomas", bio: "Walter Theodore 'Sonny' Rollins[1][2] (born September 7, 1930)[3] is an American jazz tenor saxophonist who is widely recognized as one of the most important and influential jazz musicians.[3] In a seven-decade career, he has recorded over sixty albums as a leader. A number of his compositions, including 'St. Thomas', 'Oleo', 'Doxy', 'Pent-Up House', and 'Airegin', have become jazz standards. Rollins has been called 'the greatest living improviser'[4] and the 'Saxophone Colossus'.", url: "https://www.youtube.com/watch?v=cneBpjwfxhg", era: hard_bop)
Artist.create(name: "Clifford Brown", album: "New Star On The Horizon ", bio: "Clifford Benjamin Brown[1] (October 30, 1930 – June 26, 1956) was an American jazz trumpeter. He died at the age of 25 in a car accident,[2] leaving behind four years' worth of recordings. He was also a composer of note: his compositions 'Sandu', 'Joy Spring',[3] and 'Daahoud'[4] have become jazz standards.[5]

Brown won the Down Beat critics' poll for New Star of the Year in 1954; he was inducted into the DownBeat Jazz Hall of Fame in 1972 in the critics' poll.[2] He influenced later jazz trumpeters such as Booker Little, Freddie Hubbard, and Lee Morgan.", url: "https://www.youtube.com/watch?v=9iuP3CfFZDQ", era: hard_bop)
Artist.create(name: "Cannonball Adderly", album: "Something Else", bio: "ulian Edwin 'Cannonball' Adderley (September 15, 1928 – August 8, 1975) was an American jazz alto saxophonist of the hard bop era of the 1950s and 1960s.[2][3][4]

Adderley is remembered for his 1966 soul jazz single 'Mercy, Mercy, Mercy.'[5] It was written for him by Joe Zawinul and became a major crossover hit on the pop charts. A cover version by the Buckinghams also reached #5 on the charts. Adderley worked with trumpeter Miles Davis, on his own 1958 Somethin' Else album, and on the seminal Davis records Milestones (1958) and Kind of Blue (1959). He was the elder brother of jazz trumpeter Nat Adderley, a longtime member of his band.", url: "https://www.youtube.com/watch?v=7OtjOvLELT4", era: hard_bop)
Artist.create(name: "Charles Mingus", album: "Mingus Ah Um", bio: "Charles Mingus Jr. (April 22, 1922 – January 5, 1979) was an American jazz double bassist, pianist, composer and bandleader. A major proponent of collective improvisation, he is considered to be one of the greatest jazz musicians and composers in history,[1] with a career spanning three decades and collaborations with other jazz legends such as Louis Armstrong, Duke Ellington, Charlie Parker, Dizzy Gillespie, Dannie Richmond, and Herbie Hancock.", url: "https://www.youtube.com/watch?v=Y8x3LWVC1L4", era: hard_bop)
Artist.create(name: "Benny Golson", album: "New York Scene", bio: "Benny Golson (born January 25, 1929) is an American bebop/hard bop jazz tenor saxophonist, composer, and arranger.[1] He came to prominence with the big bands of Lionel Hampton and Dizzy Gillespie, more as a writer than a performer, before launching his solo career. Golson is known for co-founding and co-leading The Jazztet with trumpeter Art Farmer in 1959. From the late 1960s through the 1970s Golson was in demand as an arranger for film and television and thus was less active as a performer, but he and Farmer reformed the Jazztet in 1982.

In addition to 'I Remember Clifford', many of Golson's compositions have become jazz standards including 'Blues March', 'Whisper Not', and 'Killer Joe'.", url: "https://www.youtube.com/watch?v=6mhCWHITCbE", era: hard_bop)


Artist.create(name: "Albert Ayler", album: "Something Different", bio: "Albert Ayler (/ˈaɪlər/; July 13, 1936 – November 25, 1970) was an American avant-garde jazz saxophonist, singer and composer.[1]

After early experience playing R&B and bebop, Ayler began recording music during the free jazz era of the 1960s. However, some critics argue that while Ayler's style is undeniably original and unorthodox, it does not adhere to the generally accepted critical understanding of free jazz.[2] In fact, Ayler's style is difficult to categorize in any way, and it evoked incredibly strong and disparate reactions from critics and fans alike.[3] His innovations have inspired subsequent jazz musicians.", url: "https://www.youtube.com/watch?v=HnvSfW2xjMI", era: free_jazz)
Artist.create(name: "Ornette Coleman", album: "Body and Soul", bio: "Randolph Denard Ornette Coleman (March 9 or 19, 1930 – June 11, 2015)[1] was an American jazz saxophonist, violinist, trumpeter, and composer known as a principal founder of the free jazz genre, a term derived from his 1960 album Free Jazz: A Collective Improvisation.

Born in Fort Worth, Texas, Coleman began his musical career playing in local R&B and bebop groups, and eventually formed his own group in Los Angeles featuring members such as Ed Blackwell, Don Cherry, Charlie Haden, and Billy Higgins. In 1959, he released the controversial album The Shape of Jazz to Come and began a long residency at the Five Spot jazz club in New York City. His pioneering performances often dispensed with the chordal and harmony-based playing found in bebop, instead emphasizing a jarring and free approach to improvisation.[2] In the 1970s, Coleman formed the group Prime Time and explored funk and his concept of Harmolodic music.", url: "https://www.youtube.com/watch?v=daGDPwz_deo", era: free_jazz)
Artist.create(name: "Cecil Taylor", album: "Unit Structures", bio: "Cecil Percival Taylor (March 25, 1929 – April 5, 2018)[1][2][3] was an American pianist and poet.[4][5]

Taylor was classically trained and was one of the pioneers of free jazz. His music is characterized by an energetic, physical approach, resulting in complex improvisation often involving tone clusters and intricate polyrhythms. His technique has been compared to percussion. Referring to the number of keys on a standard piano, Val Wilmer used the phrase 'eighty-eight tuned drums' to describe Taylor's style.[6] He has been referred to as being 'like Art Tatum with contemporary-classical leanings'.", url: "https://www.youtube.com/watch?v=EstPgi4eMe4", era: free_jazz)
Artist.create(name: "Anthony Braxton", album: "For Alto", bio: "Anthony Braxton (born June 4, 1945)[1] is an American composer and multi-instrumentalist who is known in the genre of free jazz.[2]

Since the 1960s, he has released more than 100 albums. He plays many types of saxophone (soprano, alto, tenor, baritone, bass, contrabass, sopranino, C-melody, mezzo-soprano) and clarinet (E-flat, B-flat, contrabass), in addition to flute, alto flute, and piano.

Braxton studied philosophy at Roosevelt University. He taught at Mills College in the 1980s, and was Professor of Music at Wesleyan University from the 1990s until his retirement at the end of 2013. He taught music composition and music history, with a concentration on the avant-garde, as well as leading ensembles in performances of his compositions. In 1994, he was given a genius grant by the MacArthur Foundation. In 2013, he was named a 2014 National Endowment for the Arts Jazz Master.[", url: "https://www.youtube.com/watch?v=_0F3Uqmgt-k", era: free_jazz)
Artist.create(name: "John Coltrane", album: "Blue Train", bio: "John William Coltrane (September 23, 1926 – July 17, 1967) was an American jazz saxophonist and composer. Working in the bebop and hard bop idioms early in his career, Coltrane helped pioneer the use of modes and was at the forefront of free jazz. He led at least fifty recording sessions and appeared on many albums by other musicians, including trumpeter Miles Davis and pianist Thelonious Monk. Over the course of his career, Coltrane's music took on an increasingly spiritual dimension. He remains one of the most influential saxophonists in music history. He received numerous posthumous awards, including canonization by the African Orthodox Church and a Pulitzer Prize in 2007.[2] His second wife was pianist and harpist Alice Coltrane. The couple had three children: John Jr. (1964–1982), a bassist; Ravi (born 1965), a saxophonist; and Oran (born 1967), also a saxophonist.", url: "https://www.youtube.com/watch?v=saN1BwlxJxA", era: free_jazz)


Artist.create(name: "Eric Dolphy", album: "Out to Lunch", bio: "Eric Allan Dolphy Jr. (June 20, 1928 – June 29, 1964) was an American jazz alto saxophonist, bass clarinetist and flautist.[1] On a few occasions, he also played the clarinet and piccolo. Dolphy was one of several multi-instrumentalists to gain prominence around the time that he was active. His use of the bass clarinet helped to establish the instrument within jazz.[2][3] Dolphy extended the vocabulary and boundaries of the alto saxophone, and was among the earliest significant jazz flute soloists.[4][3]

His improvisational style was characterized by the use of wide intervals, in addition to employing an array of extended techniques to emulate the sounds of human voices and animals.[5][6][7] He used melodic lines that were 'angular, zigzagging from interval to interval, taking hairpin turns at unexpected junctures, making dramatic leaps from the lower to the upper register.'[6] Although Dolphy's work is sometimes classified as free jazz, his compositions and solos were often rooted in conventional (if highly abstracted) tonal bebop harmony.", url: "https://www.youtube.com/watch?v=vAn_gyNcvN4", era: fusion)
Artist.create(name: "Miles Davis", album: "Bitches Brew", bio: "For the double album Bitches Brew (1970), he hired Jack DeJohnette, Airto Moreira, and Bennie Maupin. The album contained long compositions, some over twenty minutes, that were never played in the studio but were constructed from several takes by Macero and Davis. Other studio techniques included splicing, multitrack recording, and tape loops.[146] Bitches Brew peaked at No. 35 on the Billboard Album chart.[147] In 1976, it was certified gold for selling over 500,000 records. By 2003, it had sold one million copies.", url: "https://www.youtube.com/watch?v=YOK1Ox9hbsM", era: fusion)
Artist.create(name: "Chick Corea", album: "Is", bio: "Armando Anthony 'Chick' Corea (born June 12, 1941) is an American jazz composer, keyboardist, bandleader and occasional percussionist.[3] His compositions 'Spain', '500 Miles High', 'La Fiesta', 'Armando's Rhumba' and 'Windows' are widely considered jazz standards.[4] As a member of Miles Davis's band in the late 1960s, he participated in the birth of jazz fusion. In the 1970s he formed Return to Forever.[3] Along with Herbie Hancock, McCoy Tyner, Keith Jarrett and Bill Evans, he is considered one of the major piano voices to emerge in jazz during the post-John Coltrane era.[5]

Corea continued to pursue multiple collaborations and to explore different musical styles throughout the 1980s and 1990s. He is also known for promoting and fundraising for a number of social issues.[6]

Corea has won 23 Grammy Awards and been nominated over 60 times", url: "https://www.youtube.com/watch?v=PiuMmW1Xwdc", era: fusion)
Artist.create(name: "Weather Report", album: "Heavy Weather", bio: "Weather Report was an American jazz fusion band active from 1970–1986. The band was founded (and initially co-led) by Austrian keyboard player Joe Zawinul, American saxophonist Wayne Shorter and Czech bassist Miroslav Vitouš. Other prominent members at various points in the band's lifespan included Jaco Pastorius, Alphonso Johnson, Victor Bailey, Chester Thompson, Peter Erskine, Airto Moreira and Alex Acuna. Throughout most of its existence, the band was a quintet consisting of Zawinul, Shorter, a bass guitarist, a drummer, and a percussionist.

The band started as a free improvising jazz group with avant-garde and experimental electronic leanings; when Vitouš left Weather Report (due mostly to creative disagreements), Zawinul increasingly steered the band towards a funky, edgy sound incorporating elements of R&B and native musics from around the world. Zawinul utilized the latest developments in synthesizer technology, and took advantage of a large variety of sounds and tone colors to make the band stand out. During the first half of their career, Weather Report were seen as one of the defining acts in modern jazz, winning the DownBeat 'best album award' five times in a row.", url: "https://www.youtube.com/watch?v=LT0ICclq8sQ", era: fusion)
Artist.create(name: "John Mclaughlin", album: "Mahavishnu Orchestra", bio: "John McLaughlin (born 4 January 1942) is an English guitarist, bandleader, and composer. A pioneer of jazz fusion, his music combines elements of jazz with rock, world music, Indian classical music, Western classical music, flamenco, and blues. After contributing to several key British groups of the early 1960s, McLaughlin made Extrapolation, his first album as a bandleader, in 1969. He then moved to the U.S., where he played with Tony Williams's group Lifetime and then with Miles Davis on his electric jazz-fusion albums In a Silent Way, Bitches Brew, Jack Johnson, and On the Corner. His 1970s electric band, the Mahavishnu Orchestra, performed a technically virtuosic and complex style of music that fused electric jazz and rock with Indian influences.", url: "https://www.youtube.com/watch?v=LcQKjffxIOY", era: fusion)

Artist.create(name: "Pat Methany", album: "Pat Methany Group", bio: "Patrick Bruce Metheny (/məˈθiːni/ mə-THEE-nee; born August 12, 1954) is an American jazz guitarist and composer.

He is the leader of the Pat Metheny Group and is also involved in duets, solo works, and other side projects. His style incorporates elements of progressive and contemporary jazz, Latin jazz, and jazz fusion.[1] Metheny has three gold albums and 20 Grammy Awards[2][3] and is the only person to win Grammys in 10 categories. He is the brother of jazz flugelhornist Mike Metheny.", url: "https://www.youtube.com/watch?v=l4jIbLYE3gQ", era: eclectic)
Artist.create(name: "Michael Brecker", album: "Steps Ahead", bio: "Michael Leonard Brecker (March 29, 1949 – January 13, 2007) was an American jazz saxophonist and composer. He was awarded 15 Grammy Awards as both performer and composer. He was awarded an Honorary Doctorate from Berklee College of Music in 2004,[3] and was inducted into the Down Beat Jazz Hall of Fame in 2007.", url: "https://www.youtube.com/watch?v=IUymU2T2cJQ", era: eclectic)
Artist.create(name: "Wynton Marsalis", album: "Black Codes", bio: "Wynton Learson Marsalis (born October 18, 1961) is an American trumpeter, composer, teacher, and artistic director of Jazz at Lincoln Center. He has promoted classical and jazz music, often to young audiences. Marsalis has won at least nine Grammy Awards, and his Blood on the Fields was the first jazz composition to win the Pulitzer Prize for Music. He is the only musician to win a Grammy Award in jazz and classical during the same year.", url: "https://www.youtube.com/watch?v=ZBJ-MmTA-eU", era: eclectic)
Artist.create(name: "Joe Lovano", album: "Trio Tapestry", bio: "Joseph Salvatore Lovano (born December 29, 1952)[1] is an American jazz saxophonist, alto clarinetist, flautist,[1] and drummer.[2] He has earned a Grammy Award and several mentions on Down Beat magazine's critics' and readers' polls. He is married to jazz singer Judi Silvano with whom he records and performs. Lovano was a longtime member of a trio led by drummer Paul Motian.", url: "https://www.youtube.com/watch?v=m9mCWJTlHZ0", era: eclectic)
Artist.create(name: "Kenny Garrett", album: "Pushing the World Away", bio: "Kenny Garrett (born October 9, 1960) is an American post-bop jazz saxophonist and flautist who gained recognition in his youth as a member of the Duke Ellington Orchestra and of Miles Davis's band. Since then, he has pursued a solo career.", url: "https://www.youtube.com/watch?v=PFNTM9aKGNY", era: eclectic)
Artist.create(name: "Don Byron", album: "Bug Music", bio: "Donald Byron (born November 8, 1958) is an American composer and multi-instrumentalist. He primarily plays clarinet but has also played bass clarinet and saxophone in a variety of genres that includes free jazz and klezmer.", url: "https://www.youtube.com/watch?v=iyqedzCBnzY", era: eclectic)
Artist.create(name: "Dave Douglas", album: "Keystone", bio: "Dave Douglas (born March 24, 1963) is an American jazz trumpeter, composer, and educator. His career includes more than fifty recordings as a leader and more than 500 published compositions. His ensembles include the Dave Douglas Quintet; Sound Prints, a quintet co-led with saxophonist Joe Lovano; Uplift, a sextet with bassist Bill Laswell; Present Joys with pianist Uri Caine and Andrew Cyrille; High Risk, an electronic ensemble with Shigeto, Jonathan Aaron, and Ian Chang; and Engage, a sextet with Jeff Parker, Tomeka Reid, Anna Webber, Nick Dunston, and Kate Gentile.", url: "https://www.youtube.com/watch?v=aOD4GVGkfRM", era: eclectic)
Artist.create(name: "Bobby Mcferrin", album: "Circle Songs", bio: "Robert Keith McFerrin Jr. (born March 11, 1950) is an American folk-jazz vocalist. He is known for his vocal techniques, such as singing fluidly but with quick and considerable jumps in pitch—for example, sustaining a melody while also rapidly alternating with arpeggios and harmonies—as well as scat singing, polyphonic overtone singing, and improvisational vocal percussion. He is widely known for performing and recording regularly as an unaccompanied solo vocal artist. He has frequently collaborated with other artists from both the jazz and classical scenes.

McFerrin's song 'Don't Worry, Be Happy' was a No. 1 U.S. pop hit in 1988 and won Song of the Year and Record of the Year honors at the 1989 Grammy Awards. McFerrin has also worked in collaboration with instrumentalists, including pianists Chick Corea, Herbie Hancock, and Joe Zawinul, drummer Tony Williams, and cellist Yo-Yo Ma. He is the father of musicians Taylor McFerrin, Jevon McFerrin and Madison McFerrin.", url: "https://www.youtube.com/watch?v=81uJZIF9TCs", era: eclectic)
Artist.create(name: "Steve Coleman", album: "", bio: "", url: "", era: eclectic)
Artist.create(name: "Cassandra Wilson", album: "", bio: "", url: "", era: eclectic)
Artist.create(name: "Dave Sanborn", album: "", bio: "", url: "", era: eclectic)
Artist.create(name: "John Scofield", album: "", bio: "", url: "", era: eclectic)
Artist.create(name: "Keith Jarrett", album: "Keith Jarrett trio", bio: "", url: "", era: eclectic)




