# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Era.destroy_all
Artist.destroy_all

early = Era.create(name: "Early Jazz/New Orleans and Chicago Dixieland")
swing = Era.create(name: "Swing/Big Band")
bebop = Era.create(name: "Bebop")
cool = Era.create(name: "Cool")
hard_bop = Era.create(name: "Hard Bop")
free_jazz = Era.create(name: "Free Jazz/Avant Garde")
fusion = Era.create(name: "Fusion/Jazz-Rock")
eclectic = Era.create(name: "Eclecticisim")


Artist.create(name: "Louis Armstrong", album: "St. Louis Blues", bio: "Armstrong was born and raised in New Orleans. Coming to prominence in the 1920s as an inventive trumpet and cornet player, Armstrong was a foundational influence in jazz, shifting the focus of the music from collective improvisation to solo performance.[4] Around 1922, he followed his mentor, Joe Oliver, to Chicago to play in the Creole Jazz Band. In Chicago, he spent time with other popular jazz musicians, reconnecting with his friend Bix Beiderbecke and spending time with Hoagy Carmichael and Lil Hardin. He earned a reputation at 'cutting contests 'and his fame reached band leader Fletcher Henderson. Henderson persuaded Armstrong to come to New York City, where he became a featured and musically influential band soloist and recording artist. Hardin became Armstrong's second wife and they returned to Chicago to play together and then he began to form his own 'Hot' jazz bands. After years of touring, he settled in Queens, and by the 1950s, he was a national musical icon, assisted in part, by his appearances on radio and in film and television, in addition to his concerts.", url: "https://www.youtube.com/watch?v=8IJzYAda1wA",era: early)
Artist.create(name: "Leon Bismark 'Bix' Beiderbecke", album: "Georgia on My Mind", bio: "Beiderbecke was one of the most influential jazz soloists of the 1920s, a cornet player noted for an inventive lyrical approach and purity of tone, with such clarity of sound that one contemporary famously described it like 'shooting bullets at a bell'. His solos on seminal recordings such as 'Singin the Blues' and 'I'm Coming, Virginia'(both 1927) demonstrate a gift for extended improvisation that heralded the jazz ballad style, in which jazz solos are an integral part of the composition. Moreover, his use of extended chords and an ability to improvise freely along harmonic as well as melodic lines are echoed in post-WWII developments in jazz. 'In a Mist' (1927) is the best known of Beiderbecke's published piano compositions, and the only one that he recorded. His piano style reflects both jazz and classical (mainly impressionist) influences. All five of his piano compositions were published by Robbins Music during his lifetime.", url: "https://www.youtube.com/watch?v=pob7zgAWeMI", era: early)
Artist.create(name: "Jelly Roll Morton", album: "Red Hot Peppers Session: Birth of the Hot, The Classic Red Hot Peppers Sessions", bio: "Ferdinand Joseph LaMothe (September 20, c. 1890 – July 10, 1941), known professionally as Jelly Roll Morton, was an American ragtime and jazz pianist, bandleader, and composer. Morton was jazz's first arranger, proving that a genre rooted in improvisation could retain its essential characteristics when notated.[2] His composition 'Jelly Roll Blues', published in 1915, was one of the first published jazz compositions. Morton also wrote 'King Porter Stomp', 'Wolverine Blues', 'Black Bottom Stomp', and 'I Thought I Heard Buddy Bolden Say', the last a tribute to New Orleans musicians from the turn of the 20th century.", url: "https://www.youtube.com/watch?v=MkGjDbKauVo", era: early)
Artist.create(name: "Sidney Bechet", album: "Texas Moaner Blues", bio: "Sidney Joseph Bechet[1] (May 14, 1897 – May 14, 1959) was an American jazz saxophonist, clarinetist, and composer. He was one of the first important soloists in jazz, beating trumpeter Louis Armstrong to the recording studio by several months. His erratic temperament hampered his career, and not until the late 1940s did he earn wide acclaim.", url: "https://www.youtube.com/watch?v=REYLNs0rh-g", era: early)
Artist.create(name: "Earl 'Fatha' Hines ", album: "Earl Hines ", bio: "Earl Kenneth Hines, also known as Earl 'Fatha'[nb 1] Hines (December 28, 1903[nb 2] – April 22, 1983), was an American jazz pianist and bandleader. He was one of the most influential figures in the development of jazz piano and, according to one source, 'one of a small number of pianists whose playing shaped the history of jazz", url: "https://www.youtube.com/watch?v=TaD4qwztS5M", era: early)


Artist.create(name: "Duke Ellington", album: "The Ellington Suites", bio: "Edward Kennedy 'Duke' Ellington (April 29, 1899 – May 24, 1974) was an American composer, pianist, and leader of a jazz orchestra, which he led from 1923 until his death over a career spanning more than six decades.[1]
Born in Washington, D.C., Ellington was based in New York City from the mid-1920s onward and gained a national profile through his orchestra's appearances at the Cotton Club in Harlem. In the 1930s, his orchestra toured in Europe. Although widely considered a pivotal figure in the history of jazz, Ellington embraced the phrase 'beyond category' as a liberating principle and referred to his music as part of the more general category of American Music.",url: "https://www.youtube.com/watch?v=qDQpZT3GhDg", era: swing)
Artist.create(name: "Count Basie", album: "Count Basie in Kansas City", bio: "William James 'Count' Basie (/ˈbeɪsi/; August 21, 1904 – April 26, 1984)[1] was an American jazz pianist, organist, bandleader, and composer. In 1935, Basie formed his own jazz orchestra, the Count Basie Orchestra, and in 1936 took them to Chicago for a long engagement and their first recording. He led the group for almost 50 years, creating innovations like the use of two 'split' tenor saxophones, emphasizing the rhythm section, riffing with a big band, using arrangers to broaden their sound, and others. Many musicians came to prominence under his direction, including the tenor saxophonists Lester Young and Herschel Evans, the guitarist Freddie Green, trumpeters Buck Clayton and Harry 'Sweets' Edison, plunger trombonist Al Grey, and singers Jimmy Rushing, Helen Humes, Thelma Carpenter, and Joe Williams.", url: "https://www.youtube.com/watch?v=hHMYhajNtNg", era: swing)
Artist.create(name: "Coleman Hawkins", album: "Rainbow Mist", bio: "Coleman Randolph Hawkins (November 21, 1904 – May 19, 1969), nicknamed 'Hawk' and sometimes 'Bean', was an American jazz tenor saxophonist.[1] One of the first prominent jazz musicians on his instrument, as Joachim E. Berendt explained: 'there were some tenor players before him, but the instrument was not an acknowledged jazz horn'. Hawkins biographer John Chilton described the prevalent styles of tenor saxophone solos prior to Hawkins as 'mooing' and 'bery belches.' Hawkins cited as influences Happy Caldwell, Stump Evans, and Prince Robinson, although he was the first to tailor his method of improvisation to the saxophone rather than imitate the techniques of the clarinet. Hawkins' virtuosic, arpeggiated approach to improvisation, with his characteristic rich, emotional, loud, and vibrato-laden tonal style, was the main influence on a generation of tenor players that included Chu Berry, Charlie Barnet, Tex Beneke, Ben Webster, Vido Musso, Herschel Evans, Buddy Tate, and Don Byas, and through them the later tenormen, Arnett Cobb, Illinois Jacquet, Flip Phillips, Ike Quebec, Al Sears,[4] Paul Gonsalves, and Lucky Thompson.[5] While Hawkins became well known with swing music during the big band era, he had a role in the development of bebop in the 1940s.", url: "https://www.youtube.com/watch?v=r1dAnw74so0", era: swing)
Artist.create(name: "Lester Young", album: "It Don't Mean a Thing", bio: "Lester Willis Young (August 27, 1909 – March 15, 1959), nicknamed 'Pres' or 'Prez', was an American jazz tenor saxophonist and occasional clarinetist.

Coming to prominence while a member of Count Basie's orchestra, Young was one of the most influential players on his instrument. In contrast to many of his hard-driving peers, Young played with a relaxed, cool tone and used sophisticated harmonies, using what one critic called 'a free-floating style, wheeling and diving like a gull, banking with low, funky riffs that pleased dancers and listeners alike'.", url: "https://www.youtube.com/watch?v=ohCOIPjyXZM", era: swing)
Artist.create(name: "Roy Eldridge", album: "The Big Band of Little Jazz ", bio: "David Roy Eldridge (January 30, 1911 – February 26, 1989), nicknamed 'Little Jazz', was an American jazz trumpet player. His sophisticated use of harmony, including the use of tritone substitutions, his virtuosic solos exhibiting a departure from the dominant style of jazz trumpet innovator Louis Armstrong, and his strong impact on Dizzy Gillespie mark him as one of the most influential musicians of the swing era and a precursor of bebop.", url: "https://www.youtube.com/watch?v=weCyhlrnXWY", era: swing)


Artist.create(name: "Dizzy Gilespie", album: "Groovin High", bio: "John Birks 'Dizzy' Gillespie (/ɡɪˈlɛspi/; October 21, 1917 – January 6, 1993) was an American jazz trumpeter, bandleader, composer, educator and singer.[2] He was a trumpet virtuoso and improviser, building on the virtuoso style of Roy Eldridge[3] but adding layers of harmonic and rhythmic complexity previously unheard in jazz. His combination of musicianship, showmanship, and wit made him a leading popularizer of the new music called bebop. His beret and horn-rimmed spectacles, his scat singing, his bent horn, pouched cheeks, and his light-hearted personality provided some of bebop's most prominent symbols.", url: "https://www.youtube.com/watch?v=2uLpjp7xkyI",era: bebop)
Artist.create(name: "Charlie Parker", album: "Billie's Bounce", bio: "Charles 'Charlie' Parker Jr. (August 29, 1920 – March 12, 1955), nicknamed 'Bird' and 'Yardbird', was an American jazz saxophonist and composer.[1] Parker was a highly influential soloist and leading figure in the development of bebop,[2] a form of jazz characterized by fast tempos, virtuosic technique, and advanced harmonies. Parker was a blazingly fast virtuoso and introduced revolutionary harmonic ideas into jazz, including rapid passing chords, new variants of altered chords, and chord substitutions. Primarily a player of the alto saxophone, Parker's tone ranged from clean and penetrating to sweet and somber.", url: "https://www.youtube.com/watch?v=02apSoxB7B4", era: bebop)
Artist.create(name: "Bud Powell", album: "The Best of Bud Powell", bio: "Earl Rudolph 'Bud' Powell (September 27, 1924 – July 31, 1966) was an American jazz pianist and composer. Along with Charlie Parker, Thelonious Monk, and Dizzy Gillespie, Powell was a leading figure in the development of bebop. His virtuosity led many to call him the Charlie Parker of the piano.[1] Powell was also a composer, and many jazz critics credit his works and his playing as having 'greatly extended the range of jazz harmony.'", url: "https://www.youtube.com/watch?v=TaSDinL6pC8", era: bebop)
Artist.create(name: "Thelonious Monk", album: "Monk's Music", bio: "Thelonious Sphere Monk[2] (/θəˈloʊniəs/, October 10, 1917[3] – February 17, 1982) was an American jazz pianist and composer. He had a unique improvisational style and made numerous contributions to the standard jazz repertoire, including ''Round Midnight', 'Blue Monk', 'Straight, No Chaser', 'Ruby, My Dear', 'In Walked Bud', and 'Well, You Neednt'. Monk is the second-most-recorded jazz composer after Duke Ellington.[4]", url: "https://www.youtube.com/watch?v=5o59Nsw7wxU", era: bebop)
Artist.create(name: "Max Roach", album: "Best Coast Jazz", bio: "Maxwell Lemuel Roach (January 10, 1924 – August 16, 2007) was an American jazz drummer and composer. A pioneer of bebop, he worked in many other styles of music, and is generally considered one of the most important drummers in history.[1][2] He worked with many famous jazz musicians, including Coleman Hawkins, Dizzy Gillespie, Charlie Parker, Miles Davis, Duke Ellington, Thelonious Monk, Abbey Lincoln, Dinah Washington, Charles Mingus, Billy Eckstine, Stan Getz, Sonny Rollins, Eric Dolphy, and Booker Little. He was inducted into the DownBeat Hall of Fame in 1980 and the Modern Drummer Hall of Fame in 1992.", url: "https://www.youtube.com/watch?v=-gNnrMZL6Uw", era: bebop)
Artist.create(name: "Dexter Gordon", album: "Dexter Rides Again", bio: "Dexter Gordon (February 27, 1923 – April 25, 1990) was an American jazz tenor saxophonist. He was among the most influential early bebop musicians, which included other greats such as Charlie Parker, Dizzy Gillespie, and Bud Powell. Gordon's height was 6 feet 6 inches (198 cm), so he was also known as 'Long Tall Dexter' and 'Sophisticated Giant'. His studio and performance career spanned over 40 years.", url: "https://www.youtube.com/watch?v=r0vhqDCy9eQ", era: bebop)
Artist.create(name: "J.J Johnson", album: "Modern Jazz Trombones", bio: "James Louis Johnson (January 22, 1924 – February 4, 2001)[1] was an American jazz trombonist, composer and arranger.

Johnson was one of the earliest trombonists to embrace bebop.", url: "https://www.youtube.com/watch?v=1ZGeYR8b-mg", era: bebop)


Artist.create(name: "Miles Davis", album: "Kind of Blue", bio: "something", url: "placeholder", era: cool)
Artist.create(name: "", album: "", bio: "", url: "", era: cool)
Artist.create(name: "", album: "", bio: "", url: "", era: cool)
Artist.create(name: "", album: "", bio: "", url: "", era: cool)
Artist.create(name: "", album: "", bio: "", url: "", era: cool)




Artist.create(name: "Pat Methany", album: "Need to research", bio: "something", url: "placeholder", era: fusion)
Artist.create(name: "", album: "", bio: "", url: "", era: fusion)
Artist.create(name: "", album: "", bio: "", url: "", era: fusion)
Artist.create(name: "", album: "", bio: "", url: "", era: fusion)
Artist.create(name: "", album: "", bio: "", url: "", era: fusion)



Artist.create(name: "Albert Ayler", album: "Getting there", bio: "something", url: "placeholder", era: free_jazz)